import { writeFileSync } from 'node:fs';
import { createPreset } from '../../web-app/src/domain/preset.ts';
import { buildImage } from '../../web-app/src/domain/storage-layout.ts';
const preset = createPreset();
Object.assign(preset.pages[0][0][0],{type:9,label:'PAGE SYNC'});
Object.assign(preset.pages[0][1][0],{type:7,value1:1});
Object.assign(preset.pages[1][1][0],{type:9,label:'SYNC TEMP'});
Object.assign(preset.pages[1][5][2],{type:3,value1:7,label:'LAST',state1:'I',state2:'II'});
Object.assign(preset.externals[0],{type:3,channel:16,value1:47,value2:0,value3:2,label:'MODO',state1:'PRESET',state2:'STOMP'});
Object.assign(preset.externals[1],{type:3,value1:50,value2:20,value3:100,label:'LONG',state1:'CLEAN',state2:'DRIVE'});
Object.assign(preset.externals[2],{type:1,value1:6,label:'DOUBLE'});
Object.assign(preset.externals[3],{type:9,channel:16,label:'PAGE QUAD'});
Object.assign(preset.externals[4],{type:2,value1:44,value2:127,tapTempo:true});
Object.assign(preset.externals[5],{type:2,value1:42,value2:127,tapTempo:false});
Object.assign(preset.externals[6],{type:8,label:'EXP MODE'});
Object.assign(preset.externals[7],{type:2,value1:12,value2:42});
Object.assign(preset.externals[8],{type:3,value1:7,label:'TOE DBL'});
const before = new Array(1024).fill(255);
before.splice(720,7,165,1,4,11,0,127,0);
writeFileSync(process.argv[2],buildImage(preset,before));
